spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET}
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope:
              - email
              - profile

  profiles:
    include: oauth

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

ngrok:
  enabled: true
  authToken: ${NGROK_AUTH_TOKEN}
  command: http 8080 --domain=mullet-teaching-wallaby.ngrok-free.app
